extends: airbnb

parserOptions:
  ecmaVersion: 5

rules:
  #Disable es6 rules since only newer versions of node support it
  no-var: 0
  prefer-template: 0
  prefer-arrow-callback: 0
  object-shorthand: 0
  prefer-rest-params: 0

  # style
  comma-dangle: [2, "never"]
  no-console: 0
  func-names: 0
  no-shadow: 0
  consistent-return: 0
  no-param-reassign: 0
  consistent-this: ["error", "self"]

  # Added
  no-path-concat: 2

env:
  node: true

globals:
  __root: true
